### PR TITLE
Support Docker

### LINKED ISSUE #21: make docker container for deployment

### PR DESCRIPTION
**Pull request by parrt**
Support Docker (Fixes #21):

```
$ cd antlr4-lab
$ mvn clean package  # has to be built first as docker copies in the jar
$ docker build --tag antlr4-lab-docker .
$ docker run -p80:80 --rm antlr4-lab-docker
```

Then just open browser to http://localhost/index.html

### CODE REVIEW

**Comment by parrt** [comment]
Heh @kaby76, are you one with Docker?  Can you check this out? @teverett?

**Comment by kaby76** [comment]
I can check later today. I have to reinstall docker....it doesn't be quiet,
asks all the time "Can I update?", like displaying advertisements.

**Comment by parrt** [comment]
ok, making some changes. apparently i don't know what I'm doing. haha

**Comment by kaby76** [comment]
Seems to work fine. But I had to do some things to get it to work on Windows/WSL2.

* In Windows:
    * Install Docker Desktop
* In WSL2/ Ubuntu:
    * sudo apt install docker.io 
    * mvn clean; mvn install
    * docker build .
    * docker image ls # get image name.
    * docker  run -d -p 127.0.0.1:80:80 -e BIND_ADDR=0.0.0.0:80 image-name-from-above
* In Windows again, run Firefox and connect to 127.0.0.1

It looks like docker binds port 80 to 0.0.0.0 by default (after installing net-tools, and doing netstat -a).

**Comment by parrt** [comment]
Thanks!  Yeah, not sure it's useful but I'll merge in case people want. I'll add your comments to info.

**Pull request merged**
