### PR TITLE
Baseline version of share API.

### PR DESCRIPTION
**Pull request by hanjoes**
#8 

Adding a "share" API which generates a UUID and stores the page content in CloudStorage.  Will follow up with more changes:
1. frontend change to display a url with the UUID - maybe just directly go to clipboard.
2. recover the content using the url generated by share. 
3. README changes to update instructions on boot the server with correct permissions.
4. ..etc.

### CODE REVIEW

**Comment by hanjoes** [comment]
The current UUID generator is quite naive, we can also try to extend it in the future to reduce the number of UUIDs needed if the content are the same (can temporarily mitigated by adding TTL for the CloudStorage data).

**Comment by parrt** [comment]
Looks great. Will look in detail soon. One nit: "Persistent" as in PersistentLayer should probably be Persistence :)

**Comment by ericvergnaud** [comment]
> The current UUID generator is quite naive, we can also try to extend it in the future to reduce the number of UUIDs needed if the content are the same (can temporarily mitigated by adding TTL for the CloudStorage data).

Yes TTL is necessary, otherwise Ter will become livid as the S3 bill grows....

**Comment by parrt** [comment]
> Yes TTL is necessary, otherwise Ter will become livid as the S3 bill grows....

haha true! Gotta keep thinking about size. Maybe not just TTL but also max size of storage before we start deleting most ancient.

**Comment by hanjoes** [comment]
image
Yup..already had 30 day retention setup ;) will send more PRs for follow-ups.

**Comment by parrt** [comment]
I wonder if we don't need a way to persist forever in order for people to submit bug reports using this sharing link. But that opens this up to abuse. dang.

**Comment by ericvergnaud** [comment]
Can't they attach the stuff to the bug report itself ?

**Comment by parrt** [comment]
Yes but this makes it easier as they don't have to cut and paste a bunch of times and it's easier for us because we can just click on the link and see the results without having to run it manually through antlr.  

An unpleasant solution to throttling is to require people to register an account with lab :(

**Comment by ericvergnaud** [comment]
we could, from the lab, fetch the attachment by pasting a link to it

**Comment by parrt** [comment]
Yeah best to have grammar/input/etc... attached to a bug.  Actually yeah, how about a button on the lab that contacted your github account and submits a new issue to antlr/antlr4 repo?

**Comment by ericvergnaud** [comment]
that would be great!

**Pull request merged**
